from tkinter import *

def display():
    var1.set("Name is "+t1.get())
    var2.set("Gender is "+rad.get())
    h=cvar1.get()+" "+cvar2.get()
    if (h!=""):
        var3.set("Hobbies are "+h)

window=Tk()
l1=Label(window,text="Enter your name")
l1.pack()
t1=Entry(window)
t1.pack()
l2=Label(window,text="Select your gender")
l2.pack()
rad=StringVar()
r1=Radiobutton(window,text="Male",variable=rad,value="male")
r1.pack()
r2=Radiobutton(window,text="Female",variable=rad,value="female")
r2.pack()
l3=Label(window,text="Select your hobbies")
l3.pack()
cvar1=StringVar()
cvar2=StringVar()
c1=Checkbutton(window,text="Singing",variable=cvar1,onvalue="singing",offvalue="")
c1.pack()
c2=Checkbutton(window,text="Dancing",variable=cvar2,onvalue="dancing",offvalue="")
c2.pack()
var1=StringVar()
var2=StringVar()
var3=StringVar()
l4=Label(window,textvariable=var1)
l4.pack()
l5=Label(window,textvariable=var2)
l5.pack()
l6=Label(window,textvariable=var3)
l6.pack()
b1=Button(window,text="Submit",command=display)
b1.pack()
window.mainloop()
